"""empty message

Revision ID: 0ac302c06412
Revises: 4f866eb4a5fe
Create Date: 2025-04-14 21:09:04.232919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac302c06412'
down_revision = '4f866eb4a5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.alter_column('meal_source',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.alter_column('meal_source',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
