"""empty message

Revision ID: 47a8a4bd72fa
Revises: 5dc2d608f5f7
Create Date: 2025-04-14 20:33:34.152998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a8a4bd72fa'
down_revision = '5dc2d608f5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_title', sa.String(length=64), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_column('meal_title')

    # ### end Alembic commands ###