"""Change time fields to Time type

Revision ID: 5dc2d608f5f7
Revises: a44858e11593
Create Date: 2025-04-11 21:51:02.046049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc2d608f5f7'
down_revision = 'a44858e11593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_plan', schema=None) as batch_op:
        batch_op.alter_column('activity_start_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('activity_end_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_plan', schema=None) as batch_op:
        batch_op.alter_column('activity_end_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('activity_start_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
