"""empty message

Revision ID: 6f77f1de8c5a
Revises: b5a85368faaf
Create Date: 2025-04-24 10:35:41.856570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f77f1de8c5a'
down_revision = 'b5a85368faaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_family_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_active_family', 'family', ['active_family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_active_family', type_='foreignkey')
        batch_op.drop_column('active_family_id')

    # ### end Alembic commands ###
