"""empty message

Revision ID: 7cfa19112961
Revises: 8580a3b3e9d3
Create Date: 2025-01-16 15:17:52.343240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfa19112961'
down_revision = '8580a3b3e9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entry_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vrn', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('fuel_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_mileage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fuel_cost', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entry_log', schema=None) as batch_op:
        batch_op.drop_column('fuel_cost')
        batch_op.drop_column('vehicle_mileage')
        batch_op.drop_column('fuel_price')
        batch_op.drop_column('vrn')
        batch_op.drop_column('entry_date')

    # ### end Alembic commands ###
