"""empty message

Revision ID: 92818f86f07e
Revises: 7cfa19112961
Create Date: 2025-01-20 13:08:38.412779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92818f86f07e'
down_revision = '7cfa19112961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entry_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_miles', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entry_log', schema=None) as batch_op:
        batch_op.drop_column('actual_miles')

    # ### end Alembic commands ###
