"""empty message

Revision ID: a44858e11593
Revises: ed02352e5f55
Create Date: 2025-04-11 00:50:14.112376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44858e11593'
down_revision = 'ed02352e5f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('activity_end_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('activity_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_plan', schema=None) as batch_op:
        batch_op.alter_column('activity_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('activity_end_date')
        batch_op.drop_column('activity_start_date')

    # ### end Alembic commands ###
