"""empty message

Revision ID: b5a85368faaf
Revises: 697c7364abfc
Create Date: 2025-04-17 21:46:23.534861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a85368faaf'
down_revision = '697c7364abfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_code', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('uq_family_invitation_code', ['invitation_code'])  # Added constraint name

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_constraint('uq_family_invitation_code', type_='unique')  # Use the same constraint name
        batch_op.drop_column('invitation_code')

    # ### end Alembic commands ###