"""empty message

Revision ID: d775448dfdcd
Revises: 92818f86f07e
Create Date: 2025-01-22 09:42:45.482736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd775448dfdcd'
down_revision = '92818f86f07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entry_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('litres', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gallon', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mpg', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entry_log', schema=None) as batch_op:
        batch_op.drop_column('mpg')
        batch_op.drop_column('gallon')
        batch_op.drop_column('litres')

    # ### end Alembic commands ###
