"""empty message

Revision ID: ed02352e5f55
Revises: 00b23b1da8ca
Create Date: 2025-04-11 00:43:19.790551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed02352e5f55'
down_revision = '00b23b1da8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('activity_title', sa.String(length=64), nullable=False),
    sa.Column('activity_all_day_event', sa.Boolean(), nullable=True),
    sa.Column('activity_start_time', sa.DateTime(), nullable=True),
    sa.Column('activity_end_time', sa.DateTime(), nullable=True),
    sa.Column('activity_description', sa.String(length=500), nullable=True),
    sa.Column('activity_location', sa.String(length=500), nullable=True),
    sa.Column('activity_comments', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_plan')
    # ### end Alembic commands ###
