"""Remove VehicleData and FuelEntryLog tables

Revision ID: ff9dd7f070d8
Revises: 6f77f1de8c5a
Create Date: 2025-05-06 19:49:28.409448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9dd7f070d8'
down_revision = '6f77f1de8c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_data')
    op.drop_table('fuel_entry_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_entry_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('entry_date', sa.DATETIME(), nullable=True),
    sa.Column('vrn', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fuel_price', sa.INTEGER(), nullable=True),
    sa.Column('vehicle_mileage', sa.INTEGER(), nullable=True),
    sa.Column('fuel_cost', sa.INTEGER(), nullable=True),
    sa.Column('actual_miles', sa.INTEGER(), nullable=True),
    sa.Column('litres', sa.INTEGER(), nullable=True),
    sa.Column('gallon', sa.INTEGER(), nullable=True),
    sa.Column('mpg', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('vehicle_nickname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('vrn', sa.VARCHAR(length=64), nullable=True),
    sa.Column('vehicle_make', sa.VARCHAR(length=64), nullable=True),
    sa.Column('vehicle_model', sa.VARCHAR(length=64), nullable=True),
    sa.Column('vehicle_fuel_tank_size', sa.INTEGER(), nullable=True),
    sa.Column('vehicle_fuel_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('vehicle_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
